<select>
  <option value="pokoj">Pokój</option>
  <option value="garaz">Garaż</option>
  <option value="salon">Salon</option>
  <option value="lazienka">Łazienka</option>
  <option value="kuchnia">Kuchnia</option>
</select>
<br/>
<div id="tempall" style="height: 400px; min-width: 310px; width:100%;"></div>
<br/>
<div id="odczyt_temp_1" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
