<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
  <head>
      <title><?php echo $this->tytul ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/style.css')?>" />
    <!--<link rel="stylesheet" type="text/css" href="css/style.css" />-->
    <!--<link rel="stylesheet" type="text/css" href="css/print.css" media="print" />-->
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery-1.9.1.js')?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/tempjavascript.js')?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/tempall.js')?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/highcharts.js')?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/modules/exporting.js')?>"></script>
  </head>

    
<body>
   <div id="pojemnik">
       <!--początek pojemnika-->
    <?php if ($this->identity): ?>
       <div class="menu">
           <a href="<?php echo $this->url(array(
               'controller' => 'index',
               'action' => 'index'
               )) ?>"><span>Strona główna</span></a>
           
           <a href="<?php echo $this->url(array(
               'controller' => 'index',
               'action' => 'monitoring'
               )) ?>"><span>Monitoring</span></a>
           
           <a href="<?php echo $this->url(array(
               'controller' => 'index',
               'action' => 'temperatura'
               )) ?>"><span>Temperatura</span></a>
           
           <a href="<?php echo $this->url(array(
               'controller' => 'index',
               'action' => 'kontrola'
               )) ?>"><span>Kontrola wejść i wyjść</span></a>

           <a class="last" href="<?php echo $this->url(array(
               'controller' => 'autoryzacja',
               'action' => 'wylogowanie'
               )) ?>"><span>Wyloguj</span></a>           
       
       
   </div>
    <!--koniec pojemnika-->
    <?php endif; ?>

        <div class="header">
            <h1><span>Praca inżynierska</span></h1>
            <h2><span>Projekt systemu i monitoringu domu jednorodzinnego w oparciu o otwarte oprogramowanie i komercyjne urządzenia sieciowe</span></h2>
        </div>
        <div class="content">
           <?php echo $this->layout()->content; ?>
        </div>
       
        <div class="footer">
            <span>Dariusz Haraf &#169</span>
        </div>

    </div>
</body>    
    
</html>